apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-registry
  labels:
    app: registry
spec:
  storageClassName: nfs-service
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

