apiVersion: v1
kind: Service
metadata:
  name: svc-registry 
  labels:
    app: dep-registry
spec:
  ports:
  - port: 5000
    protocol: TCP 
    targetPort: 5000
  type: NodePort
  selector:
    app: dep-registry
