apiVersion: v1
kind: Service
metadata:
  name: influx-svc
  labels:
    app: monitor
spec:
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8086
  type: ClusterIP
  selector:
    app: monitor
    sub: influx

