apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: monitor
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
  selector:
    app: monitor
    sub: grafana

